edition = "2024"
style_edition = "2024"
comment_width = 120
format_code_in_doc_comments = false
format_macro_bodies = true
format_macro_matchers = true
normalize_comments = false
normalize_doc_attributes = false
reorder_impl_items = true
reorder_imports = false
tab_spaces = 4
wrap_comments = false
